"""empty message

Revision ID: 37131f7f5f51
Revises: 21d6240ab658
Create Date: 2023-07-17 18:35:36.538305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37131f7f5f51'
down_revision = '21d6240ab658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
